// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: api/proto/goproc/v1/goproc.proto

package goprocv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            string                 `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"` // MVP: just a PID
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Groups        []string               `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{2}
}

func (x *AddRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AddRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AddRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{3}
}

func (x *AddResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Pids          []int32                `protobuf:"varint,2,rep,packed,name=pids,proto3" json:"pids,omitempty"`
	TagsAny       []string               `protobuf:"bytes,3,rep,name=tags_any,json=tagsAny,proto3" json:"tags_any,omitempty"`
	TagsAll       []string               `protobuf:"bytes,4,rep,name=tags_all,json=tagsAll,proto3" json:"tags_all,omitempty"`
	GroupsAny     []string               `protobuf:"bytes,5,rep,name=groups_any,json=groupsAny,proto3" json:"groups_any,omitempty"`
	GroupsAll     []string               `protobuf:"bytes,6,rep,name=groups_all,json=groupsAll,proto3" json:"groups_all,omitempty"`
	AliveOnly     bool                   `protobuf:"varint,7,opt,name=alive_only,json=aliveOnly,proto3" json:"alive_only,omitempty"`
	TextSearch    string                 `protobuf:"bytes,8,opt,name=text_search,json=textSearch,proto3" json:"text_search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListRequest) GetPids() []int32 {
	if x != nil {
		return x.Pids
	}
	return nil
}

func (x *ListRequest) GetTagsAny() []string {
	if x != nil {
		return x.TagsAny
	}
	return nil
}

func (x *ListRequest) GetTagsAll() []string {
	if x != nil {
		return x.TagsAll
	}
	return nil
}

func (x *ListRequest) GetGroupsAny() []string {
	if x != nil {
		return x.GroupsAny
	}
	return nil
}

func (x *ListRequest) GetGroupsAll() []string {
	if x != nil {
		return x.GroupsAll
	}
	return nil
}

func (x *ListRequest) GetAliveOnly() bool {
	if x != nil {
		return x.AliveOnly
	}
	return false
}

func (x *ListRequest) GetTextSearch() string {
	if x != nil {
		return x.TextSearch
	}
	return ""
}

type Proc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Pgid          int32                  `protobuf:"varint,3,opt,name=pgid,proto3" json:"pgid,omitempty"`
	Cmd           string                 `protobuf:"bytes,4,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Alive         bool                   `protobuf:"varint,5,opt,name=alive,proto3" json:"alive,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Groups        []string               `protobuf:"bytes,7,rep,name=groups,proto3" json:"groups,omitempty"`
	AddedAtUnix   int64                  `protobuf:"varint,8,opt,name=added_at_unix,json=addedAtUnix,proto3" json:"added_at_unix,omitempty"`
	LastSeenUnix  int64                  `protobuf:"varint,9,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"` // Metrics will be added later (cpu%, rss, io)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proc) Reset() {
	*x = Proc{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proc) ProtoMessage() {}

func (x *Proc) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proc.ProtoReflect.Descriptor instead.
func (*Proc) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{5}
}

func (x *Proc) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Proc) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Proc) GetPgid() int32 {
	if x != nil {
		return x.Pgid
	}
	return 0
}

func (x *Proc) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Proc) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *Proc) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Proc) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Proc) GetAddedAtUnix() int64 {
	if x != nil {
		return x.AddedAtUnix
	}
	return 0
}

func (x *Proc) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Procs         []*Proc                `protobuf:"bytes,1,rep,name=procs,proto3" json:"procs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetProcs() []*Proc {
	if x != nil {
		return x.Procs
	}
	return nil
}

type KillRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*KillRequest_Id
	//	*KillRequest_Pid
	Target        isKillRequest_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{7}
}

func (x *KillRequest) GetTarget() isKillRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *KillRequest) GetId() uint64 {
	if x != nil {
		if x, ok := x.Target.(*KillRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *KillRequest) GetPid() int32 {
	if x != nil {
		if x, ok := x.Target.(*KillRequest_Pid); ok {
			return x.Pid
		}
	}
	return 0
}

type isKillRequest_Target interface {
	isKillRequest_Target()
}

type KillRequest_Id struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type KillRequest_Pid struct {
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3,oneof"`
}

func (*KillRequest_Id) isKillRequest_Target() {}

func (*KillRequest_Pid) isKillRequest_Target() {}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{8}
}

type RmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmRequest) Reset() {
	*x = RmRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmRequest) ProtoMessage() {}

func (x *RmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmRequest.ProtoReflect.Descriptor instead.
func (*RmRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{9}
}

func (x *RmRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmResponse) Reset() {
	*x = RmResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmResponse) ProtoMessage() {}

func (x *RmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmResponse.ProtoReflect.Descriptor instead.
func (*RmResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{10}
}

type RenameTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameTagRequest) Reset() {
	*x = RenameTagRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameTagRequest) ProtoMessage() {}

func (x *RenameTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameTagRequest.ProtoReflect.Descriptor instead.
func (*RenameTagRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{11}
}

func (x *RenameTagRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RenameTagRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type RenameTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       uint32                 `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameTagResponse) Reset() {
	*x = RenameTagResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameTagResponse) ProtoMessage() {}

func (x *RenameTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameTagResponse.ProtoReflect.Descriptor instead.
func (*RenameTagResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{12}
}

func (x *RenameTagResponse) GetUpdated() uint32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type RenameGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameGroupRequest) Reset() {
	*x = RenameGroupRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameGroupRequest) ProtoMessage() {}

func (x *RenameGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameGroupRequest.ProtoReflect.Descriptor instead.
func (*RenameGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{13}
}

func (x *RenameGroupRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RenameGroupRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type RenameGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       uint32                 `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameGroupResponse) Reset() {
	*x = RenameGroupResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameGroupResponse) ProtoMessage() {}

func (x *RenameGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameGroupResponse.ProtoReflect.Descriptor instead.
func (*RenameGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{14}
}

func (x *RenameGroupResponse) GetUpdated() uint32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{15}
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{16}
}

var File_api_proto_goproc_v1_goproc_proto protoreflect.FileDescriptor

const file_api_proto_goproc_v1_goproc_proto_rawDesc = "" +
	"\n" +
	" api/proto/goproc/v1/goproc.proto\x12\tgoproc.v1\"\r\n" +
	"\vPingRequest\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\tR\x02ok\"J\n" +
	"\n" +
	"AddRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x16\n" +
	"\x06groups\x18\x03 \x03(\tR\x06groups\"\x1d\n" +
	"\vAddResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xe7\x01\n" +
	"\vListRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\x12\x12\n" +
	"\x04pids\x18\x02 \x03(\x05R\x04pids\x12\x19\n" +
	"\btags_any\x18\x03 \x03(\tR\atagsAny\x12\x19\n" +
	"\btags_all\x18\x04 \x03(\tR\atagsAll\x12\x1d\n" +
	"\n" +
	"groups_any\x18\x05 \x03(\tR\tgroupsAny\x12\x1d\n" +
	"\n" +
	"groups_all\x18\x06 \x03(\tR\tgroupsAll\x12\x1d\n" +
	"\n" +
	"alive_only\x18\a \x01(\bR\taliveOnly\x12\x1f\n" +
	"\vtext_search\x18\b \x01(\tR\n" +
	"textSearch\"\xda\x01\n" +
	"\x04Proc\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04pgid\x18\x03 \x01(\x05R\x04pgid\x12\x10\n" +
	"\x03cmd\x18\x04 \x01(\tR\x03cmd\x12\x14\n" +
	"\x05alive\x18\x05 \x01(\bR\x05alive\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x16\n" +
	"\x06groups\x18\a \x03(\tR\x06groups\x12\"\n" +
	"\radded_at_unix\x18\b \x01(\x03R\vaddedAtUnix\x12$\n" +
	"\x0elast_seen_unix\x18\t \x01(\x03R\flastSeenUnix\"5\n" +
	"\fListResponse\x12%\n" +
	"\x05procs\x18\x01 \x03(\v2\x0f.goproc.v1.ProcR\x05procs\"=\n" +
	"\vKillRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x04H\x00R\x02id\x12\x12\n" +
	"\x03pid\x18\x02 \x01(\x05H\x00R\x03pidB\b\n" +
	"\x06target\"\x0e\n" +
	"\fKillResponse\"\x1b\n" +
	"\tRmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\f\n" +
	"\n" +
	"RmResponse\"6\n" +
	"\x10RenameTagRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"-\n" +
	"\x11RenameTagResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\rR\aupdated\"8\n" +
	"\x12RenameGroupRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"/\n" +
	"\x13RenameGroupResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\rR\aupdated\"\x0e\n" +
	"\fResetRequest\"\x0f\n" +
	"\rResetResponse2\xee\x03\n" +
	"\x06GoProc\x127\n" +
	"\x04Ping\x12\x16.goproc.v1.PingRequest\x1a\x17.goproc.v1.PingResponse\x124\n" +
	"\x03Add\x12\x15.goproc.v1.AddRequest\x1a\x16.goproc.v1.AddResponse\x127\n" +
	"\x04List\x12\x16.goproc.v1.ListRequest\x1a\x17.goproc.v1.ListResponse\x127\n" +
	"\x04Kill\x12\x16.goproc.v1.KillRequest\x1a\x17.goproc.v1.KillResponse\x121\n" +
	"\x02Rm\x12\x14.goproc.v1.RmRequest\x1a\x15.goproc.v1.RmResponse\x12F\n" +
	"\tRenameTag\x12\x1b.goproc.v1.RenameTagRequest\x1a\x1c.goproc.v1.RenameTagResponse\x12L\n" +
	"\vRenameGroup\x12\x1d.goproc.v1.RenameGroupRequest\x1a\x1e.goproc.v1.RenameGroupResponse\x12:\n" +
	"\x05Reset\x12\x17.goproc.v1.ResetRequest\x1a\x18.goproc.v1.ResetResponseB%Z#goproc/api/proto/goproc/v1;goprocv1b\x06proto3"

var (
	file_api_proto_goproc_v1_goproc_proto_rawDescOnce sync.Once
	file_api_proto_goproc_v1_goproc_proto_rawDescData []byte
)

func file_api_proto_goproc_v1_goproc_proto_rawDescGZIP() []byte {
	file_api_proto_goproc_v1_goproc_proto_rawDescOnce.Do(func() {
		file_api_proto_goproc_v1_goproc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_goproc_v1_goproc_proto_rawDesc), len(file_api_proto_goproc_v1_goproc_proto_rawDesc)))
	})
	return file_api_proto_goproc_v1_goproc_proto_rawDescData
}

var file_api_proto_goproc_v1_goproc_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_goproc_v1_goproc_proto_goTypes = []any{
	(*PingRequest)(nil),         // 0: goproc.v1.PingRequest
	(*PingResponse)(nil),        // 1: goproc.v1.PingResponse
	(*AddRequest)(nil),          // 2: goproc.v1.AddRequest
	(*AddResponse)(nil),         // 3: goproc.v1.AddResponse
	(*ListRequest)(nil),         // 4: goproc.v1.ListRequest
	(*Proc)(nil),                // 5: goproc.v1.Proc
	(*ListResponse)(nil),        // 6: goproc.v1.ListResponse
	(*KillRequest)(nil),         // 7: goproc.v1.KillRequest
	(*KillResponse)(nil),        // 8: goproc.v1.KillResponse
	(*RmRequest)(nil),           // 9: goproc.v1.RmRequest
	(*RmResponse)(nil),          // 10: goproc.v1.RmResponse
	(*RenameTagRequest)(nil),    // 11: goproc.v1.RenameTagRequest
	(*RenameTagResponse)(nil),   // 12: goproc.v1.RenameTagResponse
	(*RenameGroupRequest)(nil),  // 13: goproc.v1.RenameGroupRequest
	(*RenameGroupResponse)(nil), // 14: goproc.v1.RenameGroupResponse
	(*ResetRequest)(nil),        // 15: goproc.v1.ResetRequest
	(*ResetResponse)(nil),       // 16: goproc.v1.ResetResponse
}
var file_api_proto_goproc_v1_goproc_proto_depIdxs = []int32{
	5,  // 0: goproc.v1.ListResponse.procs:type_name -> goproc.v1.Proc
	0,  // 1: goproc.v1.GoProc.Ping:input_type -> goproc.v1.PingRequest
	2,  // 2: goproc.v1.GoProc.Add:input_type -> goproc.v1.AddRequest
	4,  // 3: goproc.v1.GoProc.List:input_type -> goproc.v1.ListRequest
	7,  // 4: goproc.v1.GoProc.Kill:input_type -> goproc.v1.KillRequest
	9,  // 5: goproc.v1.GoProc.Rm:input_type -> goproc.v1.RmRequest
	11, // 6: goproc.v1.GoProc.RenameTag:input_type -> goproc.v1.RenameTagRequest
	13, // 7: goproc.v1.GoProc.RenameGroup:input_type -> goproc.v1.RenameGroupRequest
	15, // 8: goproc.v1.GoProc.Reset:input_type -> goproc.v1.ResetRequest
	1,  // 9: goproc.v1.GoProc.Ping:output_type -> goproc.v1.PingResponse
	3,  // 10: goproc.v1.GoProc.Add:output_type -> goproc.v1.AddResponse
	6,  // 11: goproc.v1.GoProc.List:output_type -> goproc.v1.ListResponse
	8,  // 12: goproc.v1.GoProc.Kill:output_type -> goproc.v1.KillResponse
	10, // 13: goproc.v1.GoProc.Rm:output_type -> goproc.v1.RmResponse
	12, // 14: goproc.v1.GoProc.RenameTag:output_type -> goproc.v1.RenameTagResponse
	14, // 15: goproc.v1.GoProc.RenameGroup:output_type -> goproc.v1.RenameGroupResponse
	16, // 16: goproc.v1.GoProc.Reset:output_type -> goproc.v1.ResetResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_goproc_v1_goproc_proto_init() }
func file_api_proto_goproc_v1_goproc_proto_init() {
	if File_api_proto_goproc_v1_goproc_proto != nil {
		return
	}
	file_api_proto_goproc_v1_goproc_proto_msgTypes[7].OneofWrappers = []any{
		(*KillRequest_Id)(nil),
		(*KillRequest_Pid)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_goproc_v1_goproc_proto_rawDesc), len(file_api_proto_goproc_v1_goproc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goproc_v1_goproc_proto_goTypes,
		DependencyIndexes: file_api_proto_goproc_v1_goproc_proto_depIdxs,
		MessageInfos:      file_api_proto_goproc_v1_goproc_proto_msgTypes,
	}.Build()
	File_api_proto_goproc_v1_goproc_proto = out.File
	file_api_proto_goproc_v1_goproc_proto_goTypes = nil
	file_api_proto_goproc_v1_goproc_proto_depIdxs = nil
}
