// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/goproc/v1/goproc.proto

package goprocv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            string                 `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{2}
}

func (x *AddRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{3}
}

func (x *AddResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{4}
}

type Proc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Pgid          int32                  `protobuf:"varint,3,opt,name=pgid,proto3" json:"pgid,omitempty"`
	Cmd           string                 `protobuf:"bytes,4,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Alive         bool                   `protobuf:"varint,5,opt,name=alive,proto3" json:"alive,omitempty"` // Metrics will be added later (cpu%, rss, io)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proc) Reset() {
	*x = Proc{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proc) ProtoMessage() {}

func (x *Proc) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proc.ProtoReflect.Descriptor instead.
func (*Proc) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{5}
}

func (x *Proc) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Proc) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Proc) GetPgid() int32 {
	if x != nil {
		return x.Pgid
	}
	return 0
}

func (x *Proc) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Proc) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Procs         []*Proc                `protobuf:"bytes,1,rep,name=procs,proto3" json:"procs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetProcs() []*Proc {
	if x != nil {
		return x.Procs
	}
	return nil
}

type KillRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*KillRequest_Id
	//	*KillRequest_Pid
	Target        isKillRequest_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{7}
}

func (x *KillRequest) GetTarget() isKillRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *KillRequest) GetId() uint32 {
	if x != nil {
		if x, ok := x.Target.(*KillRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *KillRequest) GetPid() int32 {
	if x != nil {
		if x, ok := x.Target.(*KillRequest_Pid); ok {
			return x.Pid
		}
	}
	return 0
}

type isKillRequest_Target interface {
	isKillRequest_Target()
}

type KillRequest_Id struct {
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type KillRequest_Pid struct {
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3,oneof"`
}

func (*KillRequest_Id) isKillRequest_Target() {}

func (*KillRequest_Pid) isKillRequest_Target() {}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{8}
}

type RmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmRequest) Reset() {
	*x = RmRequest{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmRequest) ProtoMessage() {}

func (x *RmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmRequest.ProtoReflect.Descriptor instead.
func (*RmRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{9}
}

func (x *RmRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmResponse) Reset() {
	*x = RmResponse{}
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmResponse) ProtoMessage() {}

func (x *RmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_goproc_v1_goproc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmResponse.ProtoReflect.Descriptor instead.
func (*RmResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_goproc_v1_goproc_proto_rawDescGZIP(), []int{10}
}

var File_api_proto_goproc_v1_goproc_proto protoreflect.FileDescriptor

const file_api_proto_goproc_v1_goproc_proto_rawDesc = "" +
	"\n" +
	" api/proto/goproc/v1/goproc.proto\x12\tgoproc.v1\"\r\n" +
	"\vPingRequest\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\tR\x02ok\"\x1e\n" +
	"\n" +
	"AddRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"\x1d\n" +
	"\vAddResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\r\n" +
	"\vListRequest\"d\n" +
	"\x04Proc\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04pgid\x18\x03 \x01(\x05R\x04pgid\x12\x10\n" +
	"\x03cmd\x18\x04 \x01(\tR\x03cmd\x12\x14\n" +
	"\x05alive\x18\x05 \x01(\bR\x05alive\"5\n" +
	"\fListResponse\x12%\n" +
	"\x05procs\x18\x01 \x03(\v2\x0f.goproc.v1.ProcR\x05procs\"=\n" +
	"\vKillRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\rH\x00R\x02id\x12\x12\n" +
	"\x03pid\x18\x02 \x01(\x05H\x00R\x03pidB\b\n" +
	"\x06target\"\x0e\n" +
	"\fKillResponse\"\x1b\n" +
	"\tRmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\f\n" +
	"\n" +
	"RmResponse2\x9c\x02\n" +
	"\x06GoProc\x127\n" +
	"\x04Ping\x12\x16.goproc.v1.PingRequest\x1a\x17.goproc.v1.PingResponse\x124\n" +
	"\x03Add\x12\x15.goproc.v1.AddRequest\x1a\x16.goproc.v1.AddResponse\x127\n" +
	"\x04List\x12\x16.goproc.v1.ListRequest\x1a\x17.goproc.v1.ListResponse\x127\n" +
	"\x04Kill\x12\x16.goproc.v1.KillRequest\x1a\x17.goproc.v1.KillResponse\x121\n" +
	"\x02Rm\x12\x14.goproc.v1.RmRequest\x1a\x15.goproc.v1.RmResponseB%Z#goproc/api/proto/goproc/v1;goprocv1b\x06proto3"

var (
	file_api_proto_goproc_v1_goproc_proto_rawDescOnce sync.Once
	file_api_proto_goproc_v1_goproc_proto_rawDescData []byte
)

func file_api_proto_goproc_v1_goproc_proto_rawDescGZIP() []byte {
	file_api_proto_goproc_v1_goproc_proto_rawDescOnce.Do(func() {
		file_api_proto_goproc_v1_goproc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_goproc_v1_goproc_proto_rawDesc), len(file_api_proto_goproc_v1_goproc_proto_rawDesc)))
	})
	return file_api_proto_goproc_v1_goproc_proto_rawDescData
}

var file_api_proto_goproc_v1_goproc_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_goproc_v1_goproc_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: goproc.v1.PingRequest
	(*PingResponse)(nil), // 1: goproc.v1.PingResponse
	(*AddRequest)(nil),   // 2: goproc.v1.AddRequest
	(*AddResponse)(nil),  // 3: goproc.v1.AddResponse
	(*ListRequest)(nil),  // 4: goproc.v1.ListRequest
	(*Proc)(nil),         // 5: goproc.v1.Proc
	(*ListResponse)(nil), // 6: goproc.v1.ListResponse
	(*KillRequest)(nil),  // 7: goproc.v1.KillRequest
	(*KillResponse)(nil), // 8: goproc.v1.KillResponse
	(*RmRequest)(nil),    // 9: goproc.v1.RmRequest
	(*RmResponse)(nil),   // 10: goproc.v1.RmResponse
}
var file_api_proto_goproc_v1_goproc_proto_depIdxs = []int32{
	5,  // 0: goproc.v1.ListResponse.procs:type_name -> goproc.v1.Proc
	0,  // 1: goproc.v1.GoProc.Ping:input_type -> goproc.v1.PingRequest
	2,  // 2: goproc.v1.GoProc.Add:input_type -> goproc.v1.AddRequest
	4,  // 3: goproc.v1.GoProc.List:input_type -> goproc.v1.ListRequest
	7,  // 4: goproc.v1.GoProc.Kill:input_type -> goproc.v1.KillRequest
	9,  // 5: goproc.v1.GoProc.Rm:input_type -> goproc.v1.RmRequest
	1,  // 6: goproc.v1.GoProc.Ping:output_type -> goproc.v1.PingResponse
	3,  // 7: goproc.v1.GoProc.Add:output_type -> goproc.v1.AddResponse
	6,  // 8: goproc.v1.GoProc.List:output_type -> goproc.v1.ListResponse
	8,  // 9: goproc.v1.GoProc.Kill:output_type -> goproc.v1.KillResponse
	10, // 10: goproc.v1.GoProc.Rm:output_type -> goproc.v1.RmResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_goproc_v1_goproc_proto_init() }
func file_api_proto_goproc_v1_goproc_proto_init() {
	if File_api_proto_goproc_v1_goproc_proto != nil {
		return
	}
	file_api_proto_goproc_v1_goproc_proto_msgTypes[7].OneofWrappers = []any{
		(*KillRequest_Id)(nil),
		(*KillRequest_Pid)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_goproc_v1_goproc_proto_rawDesc), len(file_api_proto_goproc_v1_goproc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goproc_v1_goproc_proto_goTypes,
		DependencyIndexes: file_api_proto_goproc_v1_goproc_proto_depIdxs,
		MessageInfos:      file_api_proto_goproc_v1_goproc_proto_msgTypes,
	}.Build()
	File_api_proto_goproc_v1_goproc_proto = out.File
	file_api_proto_goproc_v1_goproc_proto_goTypes = nil
	file_api_proto_goproc_v1_goproc_proto_depIdxs = nil
}
